name: Build & Test

on:
  push:
    branches: [ main, master ]
  pull_request: {}

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        std: [14, 20, 23]
        compiler: [gcc, clang, msvc]
        exclude:
          # Linux: [gcc, clang]
          - os: ubuntu-latest
            compiler: msvc
          # MacOS: [clang]
          - os: macos-latest
            compiler: gcc
          - os: macos-latest
            compiler: msvc

          # Windows: [msvc]
          - os: windows-latest
            compiler: gcc
          - os: windows-latest
            compiler: clang

    name: ${{ matrix.os }} | C++${{ matrix.std }} | ${{ matrix.compiler }}

    steps:
      - uses: actions/checkout@v4
      - uses: seanmiddleditch/gha-setup-ninja@v5

      - name: Setup compiler (Linux/macOS)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          if [ "${{ runner.os }}" = "Linux" ]; then
            if [ "${{ matrix.compiler }}" = "gcc" ]; then
              sudo apt update -y
              sudo apt install -y g++-11
              echo "CXX=g++-11" >> $GITHUB_ENV
            else
              sudo apt update -y
              sudo apt install -y clang-15
              echo "CXX=clang++-15" >> $GITHUB_ENV
            fi
          else
            echo "CXX=clang++" >> $GITHUB_ENV
          fi

      - name: Print compiler info
        if: runner.os != 'Windows'
        shell: bash
        run: |
          cmake --version
          $CXX --version

      - name: Configure
        if: runner.os != 'Windows'
        shell: bash
        run: |
          if [ "${{ matrix.compiler }}" = "gcc" ]; then
            CMAKE_CXX_FLAGS="-Wall -Wextra -Wpedantic -Werror -Wno-array-bounds"
          else
            CMAKE_CXX_FLAGS="-Wall -Wextra -Wpedantic -Werror"
          fi
          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_CXX_STANDARD=${{ matrix.std }} \
            -DCMAKE_CXX_STANDARD_REQUIRED=ON \
            -DBUILD_TESTING=ON \
            -DEXAMPLES=ON \
            -DCMAKE_CXX_FLAGS="$CMAKE_CXX_FLAGS"

      - name: Build
        if: runner.os != 'Windows'
        shell: bash
        run: cmake --build build --parallel

      - name: Run tests
        if: runner.os != 'Windows'
        shell: bash
        run: ctest --test-dir build --output-on-failure

      - name: Run examples (Linux only)
        if: runner.os == 'Linux'
        shell: bash
        run: |
          if [ -d build/examples ]; then
            echo "Running examples..."
            find build/examples -maxdepth 1 -type f -executable -print -exec {} \;
          else
            echo "No examples directory found."
          fi

      - name: Setup MSVC
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Print compiler info (MSVC)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          cmake --version
          cl

      - name: Configure (MSVC)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          cmake -S . -B build -G "Ninja" ^
          -DCMAKE_BUILD_TYPE=Release ^
          -DCMAKE_CXX_STANDARD=${{ matrix.std }} ^
          -DCMAKE_CXX_STANDARD_REQUIRED=ON ^
          -DBUILD_TESTING=ON ^
          -DEXAMPLES=ON ^
          -DCMAKE_CXX_FLAGS="/W4 /WX /EHsc"

      - name: Build (MSVC)
        if: runner.os == 'Windows'
        shell: cmd
        run: cmake --build build --parallel

      - name: Run tests (MSVC)
        if: runner.os == 'Windows'
        shell: cmd
        run: ctest --test-dir build --output-on-failure

